version: '3'
services:
  php-app:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'abcd-1234'
      MYSQL_DATABASE: simple_login
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql